[server]
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"

[client]
showSidebarNavigation = false

[global]
disableWatchdogWarning = true

[runner]
magicEnabled = false

[client]
toolbarMode = "minimal"
